program: main.py
method: bayes
metric:
  name: test_loss
  goal: minimize
parameters:
    learning_rate:
      min: 1e-6
      max: 1e-3
    epoch_num:
      distribution: constant
      value: 50
    batch_size:
      min: 32
      max: 1024
    plot_freq:
      distribution: constant
      value: 1
    architecture:
      values: ['network_1', 'network_11']
    node_number:
      min: 50
      max: 500
    criterion:
      values: ['MSE']
    optimalizer:
      values: ['NAdam','Adam']
    test_signal:
      values: ['gauss']
    weight_decay:
      min: 0.0
      max: 0.1
      