program: main.py
method: bayes
metric:
  name: loss
  goal: minimize
parameters:
    learning_rate:
      min: 0.0000001
      max: 0.01
    epoch_num:
      distribution: constant
      value: 35
    batch_size:
      values: [1000,2000]
    plot_freq:
      distribution: constant
      value: 3 
    architecture:
      values: ['network_1','network_3', 'network_4', 'network_5', 'network_6']
    node_number:
      values: [200, 400, 800, 1200, 2000]
    