program: main.py
method: bayes
metric:
  name: loss
  goal: minimize
parameters:
    learning_rate:
      min: 0.0000001
      max: 0.01
    epoch_num:
      distribution: constant
      value: 10
    batch_size:
      values: [1000]
    plot_freq:
      distribution: constant
      value: 3 
    architecture:
      values: ['network_7']
    node_number:
      values: [100 ,200, 400]
    