program: main.py
method: bayes
metric:
  name: loss
  goal: minimize
parameters:
    learning_rate:
      min: 0.0000001
      max: 0.001
    epoch_num:
      distribution: constant
      value: 30
    batch_size:
      distribution: constant
      value: 5
    plot_freq:
      distribution: constant
      value: 3 
    architecture:
      values: ['network_3']
    node_number:
      values: [100]
    
