program: main.py
method: bayes
metric:
  name: test_loss
  goal: minimize
parameters:
    learning_rate:
      min: 0.0009
      max: 0.0001
    epoch_num:
      distribution: constant
      value: 20
    plot_freq:
      distribution: constant
      value: 4
    architecture:
      values: ['network_0', 'network_11']
    node_number:
      distribution: constant
      value: 150
    criterion:
      values: ['MSEsmooth']
    optimalizer:
      values: ['Adam']
    test_signal:
      values: ['gauss']
    initial_signal:
      values: ['exponential']
    weight_decay:
      min: 0.0
      max: 0.1
      