program: main.py
method: bayes
metric:
  name: loss
  goal: minimize
parameters:
    learning_rate:
      min: 0.0000001
      max: 0.001
    epoch_num:
      distribution: constant
      value: 10
    batch_size:
      values: [1000]
    plot_freq:
      distribution: constant
      value: 1
    architecture:
      values: ['network_7']
    node_number:
      values: [200, 400]
    criterion:
      values: ['MSE']
    optimalizer:
      values: ['NAdam']
    