program: main.py
method: bayes
metric:
  name: test_loss
  goal: minimize
parameters:
    learning_rate:
      min: 0.000001
      max: 0.01
    epoch_num:
      distribution: constant
      value: 15
    batch_size:
      min: 100
      max: 5000
    plot_freq:
      distribution: constant
      value: 3
    architecture:
      values: ['network_1', 'network_11']
    node_number:
      min: 50
      max: 500
    criterion:
      values: ['MSE']
    optimalizer:
      values: ['NAdam','Adam']
    test_signal:
      values: ['gauss']
    initial_signal:
      values: ['exponential']
    weight_decay:
      min: 0.0
      max: 0.1
      